#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf 0/{alpha.metal,polyMesh,uniform,T} A.*
rm -rf rayTracing
rm -rf horiz*
rm -rf *.pdf
rm -rf *.py
rm -rf *_csv
