#!/bin/bash -e
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
touch foam.foam
cp 0/alpha.metal.orig 0/alpha.metal
runApplication topoSet
mv log.topoSet log.topoSet_C0
runApplication refineMesh -dict system/refineMeshDictC0 -overwrite 
mv log.refineMesh log.refineMesh_C0
runApplication topoSet
runApplication refineMesh -dict system/refineMeshDictC1 -overwrite
runApplication setFields

if [[ "$1" == "-parallel" ]]; then
    runApplication decomposePar
    meshType="$(foamDictionary -entry dynamicFvMesh -value constant/dynamicMeshDict)"
    if [[ "$meshType" != staticFvMesh ]]; then
        # In "Decomposed Case" Paraview expect `constant` directories
        find . -maxdepth 1 -type d -regex '\./processor[0-9][0-9]*' -exec ln -s ../constant {} \;
    fi
    runParallel $application
    # Mesh reconstruction is not needed when a dynamic mesh is used
    # Use "Decomposed Case" in Paraview instead
    if [[ "$meshType" == staticFvMesh ]]; then
        runApplication reconstructPar
    fi
else
    runApplication $application
fi

runApplication ./plot_A.sh -eps -min=0.3 -max=0.9

root_dir="$(pwd | sed 's_/run/.*_/run_g')/.."
dir=rayTracing
if [[ -d "$dir" ]]; then
    "$root_dir/tools/obj2vtkseries.py" "$dir" > "$dir"/"$dir".vtk.series
    run() { runApplication "$@"; }
    for obj in $(find "$dir" -name '*.obj'); do
        vtk="${obj%obj}vtk"
        [[ -f "$vtk" ]] && continue
        run objToVTK "$obj" "$vtk"
        run() { "$@" >> log.objToVTK; }
    done
fi
echo "All is done!"
